import { themeQuartz } from 'ag-grid-community';

const focusShadow = '0 0 0 1px var(--ring)';

export const agGridTheme = themeQuartz.withParams({
  accentColor: 'var(--primary)',
  backgroundColor: 'var(--background)',
  borderColor: 'var(--border)',
  borderRadius: 'var(--radius)',
  browserColorScheme: 'inherit',
  chromeBackgroundColor: 'var(--card)',
  dataFontSize: '0.875rem',
  focusErrorShadow: focusShadow,
  focusShadow,
  foregroundColor: 'var(--foreground)',
  headerBackgroundColor: 'var(--card)',
  headerTextColor: 'var(--card-foreground)',
  iconColor: 'var(--foreground)',
  inputBackgroundColor: 'var(--background)',
  inputBorder: { color: 'var(--input)' },
  inputBorderRadius: 'calc(var(--radius) - 2px)',
  inputDisabledBackgroundColor: 'var(--muted)',
  inputDisabledBorder: { color: 'var(--border)' },
  inputDisabledTextColor: 'var(--muted-foreground)',
  inputFocusBorder: { color: 'var(--ring)' },
  inputFocusShadow: focusShadow,
  inputFocusTextColor: 'var(--foreground)',
  inputTextColor: 'var(--foreground)',
  invalidColor: 'var(--ring)',
  menuBackgroundColor: 'var(--popover)',
  menuBorder: { color: 'var(--border)' },
  menuTextColor: 'var(--popover-foreground)',
  panelBackgroundColor: 'var(--card)',
  panelTitleBarBackgroundColor: 'var(--card)',
  panelTitleBarTextColor: 'var(--card-foreground)',
  rangeSelectionBackgroundColor: 'color-mix(in oklab, var(--accent) 35%, transparent)',
  rangeSelectionBorderColor: 'var(--ring)',
  rowHoverColor: 'color-mix(in oklab, var(--muted) 50%, transparent)',
  selectedRowBackgroundColor: 'color-mix(in oklab, var(--accent) 65%, transparent)',
  sideButtonSelectedBackgroundColor: 'var(--secondary)',
  subtleTextColor: 'color-mix(in oklab, var(--foreground) 20%, var(--muted-foreground))',
  textColor: 'color-mix(in oklab, var(--foreground) 20%, var(--muted-foreground))',
  tooltipBackgroundColor: 'var(--popover)',
  tooltipTextColor: 'var(--popover-foreground)',
  wrapperBorder: { color: 'var(--border)' },
  wrapperBorderRadius: 'var(--radius)',
});
